[tool.isort]
profile = "black"

[tool.black]
line-length = 120

[tool.flake8]
max-line-length = 120
extend-ignore = ["E203"]
exclude = [".venv"]
per-file-ignores = """
    __init__.py: F401
"""

[tool.pylint]
disable="C0114,C0115,C0116,C0301"
